# Generated by Django 5.1.6 on 2025-02-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_event_category_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event-images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, choices=[('shekvetili_arena', 'Shekvetili Arena'), ('dinamo_arena', 'Dinamo Arena'), ('meskhi_stadium', 'Meskhi Stadium')], max_length=50, null=True),
        ),
    ]
