# Generated by Django 5.1.6 on 2025-03-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_eventticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
