# Generated by Django 5.1.6 on 2025-03-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event_ticket_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventticket',
            name='ticket_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
